name: Rails - Install dependencies and run RSpec

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches-ignore: [ main ]
jobs:
  run-spec:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    services:
      postgres:
        image: postgres:13.5
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test
        ports:
          - 5432:5432
        # Add a health check
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install postgres headers
        run: |
          sudo apt-get update
          sudo apt-get install libpq-dev
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: yarn
      - name: Yarn install
        run: yarn install
      - name: Setup database
        run: bundle exec rake db:setup
      - name: Compile webpacker
        run: bundle exec rails webpacker:compile
      - name: Run RSpec
        run: bundle exec rspec --profile 10
